In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_excel(r"C:\Users\USER PC\Documents\AFRO FEM CODERS\Group project\wikipedia_dataset.xlsx")

In [4]:
data.head()

,Page,2016-01-01 00:00:00,2016-01-02 00:00:00,2016-01-03 00:00:00,2016-01-04 00:00:00,2016-01-05 00:00:00,2016-01-06 00:00:00,2016-01-07 00:00:00,2016-01-08 00:00:00,2016-01-09 00:00:00,...,2016-12-22 00:00:00,2016-12-23 00:00:00,2016-12-24 00:00:00,2016-12-25 00:00:00,2016-12-26 00:00:00,2016-12-27 00:00:00,2016-12-28 00:00:00,2016-12-29 00:00:00,2016-12-30 00:00:00,2016-12-31 00:00:00
0,.xxx_en.wikipedia.org_all-access_all-agents,7089,7592,7436,7032,6498,6887,7209,7022,7194,...,4931.0,4034.0,5204.0,4331.0,4572.0,4509.0,5392.0,4950.0,2931.0,4101.0
1,.xxx_en.wikipedia.org_mobile-web_all-agents,6182,6447,6437,5912,5205,5770,5998,5948,6165,...,4617.0,3663.0,4882.0,4028.0,4263.0,4176.0,5068.0,4539.0,2666.0,3754.0
2,1._Juli_de.wikipedia.org_desktop_all-agents,20,49,33,49,34,26,66,28,18,...,26.0,20.0,19.0,43.0,24.0,41.0,39.0,39.0,31.0,31.0
3,2014_FIFA_World_Cup_en.wikipedia.org_all-acces...,5363,6280,6297,6288,6052,6200,5935,5958,6200,...,3356.0,3366.0,2912.0,2850.0,3140.0,3379.0,3497.0,3338.0,3329.0,3550.0
4,2014_FIFA_World_Cup_en.wikipedia.org_desktop_a...,3186,3784,3832,4059,4022,4213,3985,3823,3794,...,1719.0,1593.0,1255.0,1160.0,1311.0,1468.0,1728.0,1494.0,1515.0,1464.0

In [10]:
#transpose rows and columns
data_transp=data.set_index("Page").transpose().reset_index().rename(columns={"index":"Date"})

In [11]:
#transpose rows and columns
data_transp.head()

Page,Date,.xxx_en.wikipedia.org_all-access_all-agents,.xxx_en.wikipedia.org_mobile-web_all-agents,1._Juli_de.wikipedia.org_desktop_all-agents,2014_FIFA_World_Cup_en.wikipedia.org_all-access_all-agents,2014_FIFA_World_Cup_en.wikipedia.org_desktop_all-agents,2014_FIFA_World_Cup_en.wikipedia.org_mobile-web_all-agents,2015_Copa_AmÃƒÂ©rica_en.wikipedia.org_all-access_all-agents,2015_Copa_AmÃƒÂ©rica_en.wikipedia.org_desktop_all-agents,2015_Copa_AmÃƒÂ©rica_en.wikipedia.org_mobile-web_all-agents,...,XXXX_en.wikipedia.org_all-access_all-agents,YouTube_en.wikipedia.org_all-access_all-agents,YouTube_en.wikipedia.org_desktop_all-agents,YouTube_en.wikipedia.org_mobile-web_all-agents,YouTube_ru.wikipedia.org_all-access_all-agents,Zac_Efron_en.wikipedia.org_all-access_all-agents,Zayn_Malik_en.wikipedia.org_all-access_all-agents,Zendaya_en.wikipedia.org_all-access_all-agents,Zendaya_en.wikipedia.org_mobile-web_all-agents,Zodiac_Killer_en.wikipedia.org_all-access_all-agents
0,2016-01-01,7089.0,6182.0,20.0,5363.0,3186.0,2136.0,1160.0,564.0,580.0,...,14832.0,30901.0,15751.0,14966.0,8879.0,14396.0,31663.0,7091.0,5221.0,4251.0
1,2016-01-02,7592.0,6447.0,49.0,6280.0,3784.0,2425.0,1197.0,695.0,485.0,...,15531.0,31475.0,16230.0,15067.0,10195.0,15501.0,18883.0,6062.0,4344.0,5850.0
2,2016-01-03,7436.0,6437.0,33.0,6297.0,3832.0,2403.0,838.0,443.0,390.0,...,14922.0,31009.0,15973.0,14871.0,10676.0,13176.0,19065.0,4719.0,3272.0,5833.0
3,2016-01-04,7032.0,5912.0,49.0,6288.0,4059.0,2171.0,924.0,578.0,336.0,...,14028.0,30654.0,16958.0,13556.0,10468.0,11001.0,17978.0,4303.0,2757.0,5732.0
4,2016-01-05,6498.0,5205.0,34.0,6052.0,4022.0,1968.0,878.0,530.0,338.0,...,14488.0,32235.0,18455.0,13667.0,9705.0,13986.0,16868.0,6027.0,4022.0,5274.0

In [12]:
#reshape from wide to long format
#https://towardsdatascience.com/wide-to-long-data-how-and-when-to-use-pandas-melt-stack-and-wide-to-long-7c1e0f462a98
data_transp_long=pd.melt(data_transp,id_vars=["Date"],var_name="Web",value_name="Traffic")

In [13]:
data_transp_long.head()

        Date                                          Web  Traffic
0 2016-01-01  .xxx_en.wikipedia.org_all-access_all-agents   7089.0
1 2016-01-02  .xxx_en.wikipedia.org_all-access_all-agents   7592.0
2 2016-01-03  .xxx_en.wikipedia.org_all-access_all-agents   7436.0
3 2016-01-04  .xxx_en.wikipedia.org_all-access_all-agents   7032.0
4 2016-01-05  .xxx_en.wikipedia.org_all-access_all-agents   6498.0

In [25]:
#define a function to extract language from page name
import re #https://www.w3schools.com/python/python_regex.asp
def extract_lang(page):
    res= re.search("[a-z][a-z].wikipedia.org", page)
    if res:
        print(res)
        return res[0][0:2]
    return("na")

data_transp_long["language"]= data_transp_long.Web.map(extract_lang)
#the wikimedia pages fail the

In [27]:
print(data_transp_long["language"].unique())

['en' 'de' 'zh' 'ja' 'es' 'fr' 'ru' 'na']

wikimedia pages fail the regex search hence the na. Therefore, there are 7 languages plus the media language

In [15]:
data_transp_long.head()

        Date                                          Web  Traffic language
0 2016-01-01  .xxx_en.wikipedia.org_all-access_all-agents   7089.0       en
1 2016-01-02  .xxx_en.wikipedia.org_all-access_all-agents   7592.0       en
2 2016-01-03  .xxx_en.wikipedia.org_all-access_all-agents   7436.0       en
3 2016-01-04  .xxx_en.wikipedia.org_all-access_all-agents   7032.0       en
4 2016-01-05  .xxx_en.wikipedia.org_all-access_all-agents   6498.0       en

In [16]:
#A similar function to extract mode of access
def extract_mode(page): #https://www.w3schools.com/python/python_regex.asp
    res= re.search(".org_.+_", page)
    #print (res)
    if res:
        return res[0][5:]
    return("na")

data_transp_long["access_mode"]= data_transp_long.Web.map(extract_mode)

In [17]:
data_transp_long.head()

,Date,Web,Traffic,language,access_mode
0,2016-01-01,.xxx_en.wikipedia.org_all-access_all-agents,7089.0,en,all-access_
1,2016-01-02,.xxx_en.wikipedia.org_all-access_all-agents,7592.0,en,all-access_
2,2016-01-03,.xxx_en.wikipedia.org_all-access_all-agents,7436.0,en,all-access_
3,2016-01-04,.xxx_en.wikipedia.org_all-access_all-agents,7032.0,en,all-access_
4,2016-01-05,.xxx_en.wikipedia.org_all-access_all-agents,6498.0,en,all-access_

In [19]:
#check for missing values
data_transp_long.isna().sum()

Date            0
Web             0
Traffic        87
language        0
access_mode     0
dtype: int64

In [22]:
#Remove rows and columns with null values
Final_data=data_transp_long.dropna()

In [23]:
Final_data.isna().sum()

Date           0
Web            0
Traffic        0
language       0
access_mode    0
dtype: int64

In [24]:
Final_data.to_csv(r"C:\Users\USER PC\Documents\AFRO FEM CODERS\Group project\Cleaned.csv")